#!/usr/bin/env php
<?php

use App\DirectoryContent;

require __DIR__ . '/vendor/autoload.php';

// Run the code!!
try {

    $path = $argv[1] ?? './search-me';

    $dirContent = new DirectoryContent($path);
    $dirContent->inMemory()->run();

} catch (Exception $e) {
    echo $e->getMessage();
}
