#!/usr/bin/env php
<?php

use App\DirectoryContent;

require __DIR__.'/vendor/autoload.php';

// Run the code!!
try {
    $dirContent = new DirectoryContent('./search-me');
    $dirContent->inMemory()->run();
} catch (Exception $e) {
    echo $e->getMessage();
}
